// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package logic

import (
	_ "gf-admin/internal/logic/companyDept"
	_ "gf-admin/internal/logic/companyPost"
)
