// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// CompanyDept is the golang structure of table co_company_dept for DAO operations like Where/Data.
type CompanyDept struct {
	g.Meta    `orm:"table:co_company_dept, do:true"`
	Id        interface{} // ID
	ParentId  interface{} // 父部门id
	Ancestors interface{} // 祖级列表
	Name      interface{} // 部门名称
	Email     interface{} // 邮箱
	State     interface{} // 部门状态（0正常 1停用）
	Sort      interface{} // 显示顺序
	Mobile    interface{} // 联系电话
	Leader    interface{} // 负责人
	CreatedBy interface{} // 创建人
	UpdatedBy interface{} // 修改人
	CreatedAt *gtime.Time //
	UpdatedAt *gtime.Time //
	DeletedAt *gtime.Time //
}
