
# CLI tool, only in development environment.
# https://goframe.org/pages/viewpage.action?pageId=3673173
gfcli:
  # 工具编译配置
  build:
    name:     "gf-admin-pro"
    arch:     "amd64"
    system:   "linux,darwin,windows"
    mod:      ""
    cgo:      0

  # dao生成
  gen:
    dao:
      link: "pgsql:user=postgres password=admin host=192.168.3.3 port=5432 dbname=gf-school sslmode=disable"
      tables: "co_company_dept, co_company_post"
      removePrefix: "co_"
      descriptionTag:  true
      noModelComment:  true
      withTime: false
    service:
      srcFolder: "internal/logic"
      dstFolder: "internal/service"
      overwrite: false
