// ================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// You can delete these comments if you wish manually maintain this interface file.
// ================================================================================

package service

import (
	"context"
	model "gf-admin/internal/model"

	"github.com/SupenBysz/gf-admin-community/sys_model"
)

type (
	IPost interface {
		GetPostById(ctx context.Context, id int64) (*model.PostRes, error)
		GetPostByName(ctx context.Context, name string) (*model.PostRes, error)
		HasPostByName(ctx context.Context, name string, excludeIds ...int64) bool
		QueryPostList(ctx context.Context, filter *sys_model.SearchParams) (*model.PostListRes, error)
		CreatePost(ctx context.Context, info *model.Post) (*model.PostRes, error)
		UpdatePost(ctx context.Context, info *model.Post) (*model.PostRes, error)
		DeletePost(ctx context.Context, id int64) (bool, error)
	}
)

var (
	localPost IPost
)

func Post() IPost {
	if localPost == nil {
		panic("implement not found for interface IPost, forgot register?")
	}
	return localPost
}

func RegisterPost(i IPost) {
	localPost = i
}
