// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"github.com/SupenBysz/gf-admin-community/utility/daoctl/dao_interface"
	"gf-admin/internal/dao/internal"
)

type CompanyDept = dao_interface.TIDao[internal.CompanyDeptColumns]

func NewCompanyDept(dao ...dao_interface.IDao) CompanyDept {
	return (CompanyDept)(internal.NewCompanyDeptDao(dao...))
}