// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// CompanyDept is the golang structure for table company_dept.
type CompanyDept struct {
	Id        int64       `json:"id"        description:"ID"`
	ParentId  int64       `json:"parentId"  description:"父部门id"`
	Ancestors string      `json:"ancestors" description:"祖级列表"`
	Name      string      `json:"name"      description:"部门名称"`
	Email     string      `json:"email"     description:"邮箱"`
	State     int         `json:"state"     description:"部门状态（0正常 1停用）"`
	Sort      int         `json:"sort"      description:"显示顺序"`
	Mobile    string      `json:"mobile"    description:"联系电话"`
	Leader    string      `json:"leader"    description:"负责人"`
	CreatedBy string      `json:"createdBy" description:"创建人"`
	UpdatedBy string      `json:"updatedBy" description:"修改人"`
	CreatedAt *gtime.Time `json:"createdAt" description:""`
	UpdatedAt *gtime.Time `json:"updatedAt" description:""`
	DeletedAt *gtime.Time `json:"deletedAt" description:""`
}
